// Generated by CoffeeScript 1.3.3
(function() {
  "<div id=\"portalLink\">\n    <a class=\"genu\" onclick=\"StackExchange.ready(function(){genuwine.click();});return false;\">Stack Exchange</a><a class=\"unreadCount\" title=\"unread messages in your inbox\" style=\"margin-top: 3px; opacity: 1;\">1</a>\n</div>";

  var check_stack, default_check_period, set_text, show_notification;

  default_check_period = 5 * 60 * 1000;

  set_text = function(text) {
    return chrome.browserAction.setBadgeText({
      text: "" + text
    });
  };

  show_notification = function(icon, title, text) {
    var notif;
    notif = webkitNotifications.createNotification(icon, title, text);
    return notif.show();
  };

  check_stack = function() {
    var req;
    console.log("doing request");
    req = $.get("http://www.stackoverflow.com/", function(data) {
      var $unread, unread;
      $unread = $("#portalLink a.unreadCount", data);
      unread = $unread.html();
      if (unread != null) {
        set_text(unread);
      }
      return setTimeout(check_stack, default_check_period);
    });
    return req.error(function(a, b, c) {
      alert("Error accessing SO");
      return setTimeout(check_stack, 2 * default_check_period);
    });
  };

  set_text("");

  check_stack();

}).call(this);
